#statsd:
#  # How often the client emits metrics
#  period: 5s
#  # The statsd host
#  host: 127.0.0.1
#  # The statsd port
#  port: 8125

# The address HTTP requests will listen on
http-listen-address: 0.0.0.0:80

# The address GRPC requests will listen on
grpc-listen-address: 0.0.0.0:81

# The address peers will connect too
# Should be the same as grpc-listen-address unless you are running behind
# a NAT or running in a docker container without host networking
advertise-address: localhost:81

# Max size of the cache; The cache size will never grow beyond this size.
cache-size: 50000

etcd:
  # Endpoints
  endpoints: [localhost:2379]

