version: '3'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.2
    command: >
        /usr/local/bin/etcd
        -name etcd0
        -advertise-client-urls http://localhost:2379
        -listen-client-urls http://0.0.0.0:2379
        -initial-advertise-peer-urls http://0.0.0.0:2380
        -listen-peer-urls http://0.0.0.0:2380
        -initial-cluster-token etcd-cluster-1
        -initial-cluster etcd0=http://0.0.0.0:2380
        -initial-cluster-state new
    ports:
      - "2379:2379"
  metrics:
    image: registry.postgun.com:5000/kubegun/metrics:latest
    ports:
      - "8125:8125/udp"
      - "8081:81"
      - "8080:80"
