version: '3'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.2
    command: >
      /usr/local/bin/etcd
      -name etcd0
      -advertise-client-urls http://etcd:2379
      -listen-client-urls http://0.0.0.0:2379
      -initial-advertise-peer-urls http://0.0.0.0:2380
      -listen-peer-urls http://0.0.0.0:2380
      -initial-cluster-token etcd-cluster-1
      -initial-cluster etcd0=http://0.0.0.0:2380
      -initial-cluster-state new
  gubernator-1:
    image: thrawn01/gubernator:latest
    command: "/gubernator"
    environment:
      # The address GRPC requests will listen on
      - GUBER_GRPC_ADDRESS=0.0.0.0:81
      # The address HTTP requests will listen on
      - GUBER_HTTP_ADDRESS=0.0.0.0:80
      # The address peers will connect too
      # Should be the same as grpc-listen-address unless you are running behind
      # a NAT or running in a docker container without host networking
      - GUBER_ETCD_ADVERTISE_ADDRESS=gubernator-1:81
      # Max size of the cache; The cache size will never grow beyond this size.
      - GUBER_CACHE_SIZE=50000
      # A Comma separate list of etcd nodes
      - GUBER_ETCD_ENDPOINTS=etcd:2379
    ports:
      - "8081:81"
      - "8080:80"
  gubernator-2:
    image: thrawn01/gubernator:latest
    command: "/gubernator"
    environment:
      # The address GRPC requests will listen on
      - GUBER_GRPC_ADDRESS=0.0.0.0:81
      # The address HTTP requests will listen on
      - GUBER_HTTP_ADDRESS=0.0.0.0:80
      # The address peers will connect too
      # Should be the same as grpc-listen-address unless you are running behind
      # a NAT or running in a docker container without host networking
      - GUBER_ETCD_ADVERTISE_ADDRESS=gubernator-2:81
      # Max size of the cache; The cache size will never grow beyond this size.
      - GUBER_CACHE_SIZE=50000
      # A Comma separate list of etcd nodes
      - GUBER_ETCD_ENDPOINTS=etcd:2379
    ports:
      - "8181:81"
      - "8180:80"
