# mailgun/service config
public_api_host: api.ninomail.com
protected_api_host: localhost
protected_api_url: http://localhost:9001
vulcand_namespace: /vulcand
http_port: 9040
grpc_port: 9041

logging:
  # Skip logging to stdout
  no_stdout: false
  log_level: DEBUG
#  handlers:
#    kafka:
#      log_level: INFO
#      topic: udplog
#      nodes:
#        - localhost:9092

statsd:
  # How often the client emits metrics
  period: 5s
  # The statsd host
  host: 127.0.0.1
  # The statsd port
  port: 8125


# Should be the same as grpc_port unless you are running behind
# a NAT or running in a docker container without host networking
grpc-advertise-address: localhost:9041

lru-cache:
  # Max size of the cache; The cache size will never grow beyond
  # this size.
  max-cache-size: 100000
  # The initial size of the cache; The cache may grow or shrink
  # depending on the number of rate limits the server is handling
  # currently. However the cache will never shrink lower than the
  # initial size.
  initial-cache-size: 10000
  # Interval at which gubernator should check if the cache size
  # needs to shrink or grow. Lower the inspection interval to
  # make the cache more responsive to high volume bursts, raise
  # the interval to conserve more memory during bursts.
  inspect-interval: 30s

etcd:
  # Endpoints
  endpoints: [localhost:2379]

